### ISSUE TITLE
No output if Replica Set not owned by Deployment

### ISSUE THREAD

**Issue by Bourne-ID** [aws-containers/kubectl-detector-for-docker-socket#14]
It is possible that a ReplicaSet is not owned by a Deployment but instead something else, for example ArgoRollouts. 

In the event DDS scans a pod, refers to the ReplicaSet but is owned by a Rollout, it will log 
```
> kubectl dds -n rbourne
error: deployments.apps "rollout-socket" not found%
```

However the end table is not outputted. This means a large cluster may have been scanned, Docker mounts detected but nothing is outputted. This can mislead the end user to determine no mounts exist in the cluster.

**Comment by rothgar** [comment]
Thanks for the fix in #15
