### ISSUE TITLE
Should we also detect mounts of dockershim.sock which is being deprecated?

### ISSUE THREAD

**Issue by RobertNorthard** [aws-containers/kubectl-detector-for-docker-socket#2]
The tool currently does not detect resources that mount the `dockershim.sock`, which is being deprecated and removed. Customers might mount this socket for various cluster tools (e.g. https://github.com/aws/amazon-vpc-cni-k8s/issues/1397).

**Comment by trunet** [comment]
I guess this was done on this commit: https://github.com/aws-containers/kubectl-detector-for-docker-socket/commit/69289c80f80426cafad895a2de0900df8548aa8b

**Comment by rothgar** [comment]
I think this has already been done but feel free to comment again if it's still a problem.
