### ISSUE TITLE
Outdated Krew plugin

### ISSUE THREAD

**Issue by mothershipper** [aws-containers/kubectl-detector-for-docker-socket#8]
Default plugin version on krew is 0.1.0, which misses the check for dockershim.sock

**Comment by rothgar** [comment]
I'm waiting for the krew-index maintainers to approve the PR https://github.com/kubernetes-sigs/krew-index/pull/2721

For now you can download the binary from this repos releases and use it as is.

**Comment by mothershipper** [comment]
Yup, we already built from source after noticing - figured we'd flag it in case it wasn't on the radar. Thanks for looking into it.
